package com.clevertap.rnsignedcallandroid.util

object Constants {
    const val SCAccountId = "61a52046f56a14cb19a1e9cc"
    const val SCApiKey = "9dcced09dae16c5e3606c22346d92361b77efdb360425913850bea4f22d812dd"
    const val LOG_TAG = "[CT]:[SignedCall]:[RN]"
    const val CHANNEL_NAME = "clevertap_signedcall_flutter"
    const val KEY_LOG_LEVEL = "logLevel"
    const val KEY_INIT_PROPERTIES = "initProperties"
    const val KEY_ACCOUNT_ID = "accountId"
    const val KEY_API_KEY = "apiKey"
    const val KEY_CUID = "cuid"
    const val KEY_APP_ID = "appId"
    const val KEY_NAME = "name"
    const val KEY_RINGTONE = "ringtone"
    const val KEY_ALLOW_PERSIST_SOCKET_CONNECTION = "allowPersistSocketConnection"
    const val KEY_PROMPT_RECEIVER_READ_PHONE_STATE_PERMISSION = "promptReceiverReadPhoneStatePermission"
    const val KEY_OVERRIDE_DEFAULT_BRANDING = "overrideDefaultBranding"
    const val KEY_MISSED_CALL_ACTIONS = "missedCallActions"
    const val KEY_BG_COLOR = "bgColor"
    const val KEY_FONT_COLOR = "fontColor"
    const val KEY_LOGO_URL = "logoUrl"
    const val KEY_BUTTON_THEME = "buttonTheme"
    const val KEY_CALL_PROPERTIES = "callProperties"
    const val KEY_RECEIVER_CUID = "receiverCuid"
    const val KEY_CALL_CONTEXT = "callContext"
    const val KEY_CALL_OPTIONS = "callOptions"
    const val KEY_ERROR_CODE = "errorCode"
    const val KEY_ERROR_MESSAGE = "errorMessage"
    const val KEY_ERROR_DESCRIPTION = "errorDescription"
    const val DARK_THEME = "dark"
    const val KEY_ACTION = "action"
    const val KEY_ACTION_ID = "actionId"
    const val KEY_ACTION_LABEL = "actionLabel"
    const val KEY_CALL_DETAILS = "callDetails"
    const val KEY_CALLER_CUID = "callerCuid"
    const val KEY_CALLEE_CUID = "calleeCuid"
}
