package com.clevertap.rnsignedcallandroid.internal.util

object Constants {
  const val LOG_TAG = "[CT]:[SignedCall]:[RN]"
  const val KEY_ACCOUNT_ID = "accountId"
  const val KEY_API_KEY = "apiKey"
  const val KEY_CUID = "cuid"
  const val KEY_APP_ID = "appId"
  const val KEY_NAME = "name"
  const val KEY_RINGTONE = "ringtone"
  const val KEY_ALLOW_PERSIST_SOCKET_CONNECTION = "allowPersistSocketConnection"
  const val KEY_PROMPT_PUSH_PRIMER = "promptPushPrimer"
  const val KEY_PROMPT_RECEIVER_READ_PHONE_STATE_PERMISSION =
    "promptReceiverReadPhoneStatePermission"
  const val KEY_NOTIFICATION_PERMISSION_REQUIRED =
    "notificationPermissionRequired"
  const val KEY_CALL_SCREEN_ON_SIGNALLING =
    "callScreenOnSignalling"
  const val KEY_SWIPE_OFF_BEHAVIOUR_IN_FOREGROUND_SERVICE =
    "swipeOffBehaviourInForegroundService"
  const val KEY_OVERRIDE_DEFAULT_BRANDING = "overrideDefaultBranding"
  const val KEY_MISSED_CALL_ACTIONS = "missedCallActions"
  const val KEY_BG_COLOR = "bgColor"
  const val KEY_FONT_COLOR = "fontColor"
  const val KEY_LOGO_URL = "logoUrl"
  const val KEY_BUTTON_THEME = "buttonTheme"
  const val KEY_CANCEL_COUNTDOWN_COLOR = "cancelCountdownColor"
  const val KEY_SHOW_POWERED_BY_SIGNED_CALL = "showPoweredBySignedCall"
  const val KEY_RECEIVER_CUID = "receiverCuid"
  const val KEY_CALL_CONTEXT = "callContext"
  const val KEY_INITIATOR_IMAGE = "initiatorImage"
  const val KEY_RECEIVER_IMAGE = "receiverImage"
  const val KEY_REMOTE_CONTEXT = "remoteContext"
  const val KEY_ERROR_CODE = "errorCode"
  const val KEY_ERROR_MESSAGE = "errorMessage"
  const val KEY_ERROR_DESCRIPTION = "errorDescription"
  const val DARK_THEME = "dark"
  const val KEY_ACTION = "action"
  const val KEY_ACTION_ID = "actionId"
  const val KEY_ACTION_LABEL = "actionLabel"
  const val KEY_CALL_DETAILS = "callDetails"
  const val KEY_CALL_ID = "callId"
  const val KEY_CALLER_CUID = "callerCuid"
  const val KEY_CALLEE_CUID = "calleeCuid"
  const val KEY_IS_SUCCESSFUL = "isSuccessful"
  const val KEY_ERROR = "error"
}
